# Generated by Django 4.1.7 on 2023-05-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0002_user_name_user_status_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="icon",
            field=models.ImageField(default="userBase.svg", null=True, upload_to=""),
        ),
    ]
