# Generated by Django 4.1.7 on 2023-05-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("-updated", "-created")},
        ),
    ]
