# Generated by Django 4.1.7 on 2023-05-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0004_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-updated", "-created")},
        ),
    ]
