# Generated by Django 4.1.7 on 2023-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0004_user_friends_alter_topic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="showFriendsMessages",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
