# Generated by Django 4.1.7 on 2023-05-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0007_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
