# Generated by Django 4.1.7 on 2023-05-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0010_friendshiprequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="friends",
        ),
    ]
