# Generated by Django 4.1.7 on 2023-05-29 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0011_remove_user_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="likes",
            field=models.ManyToManyField(
                related_name="comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
