# Generated by Django 4.1.7 on 2023-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0015_imagemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="ImageMessage",
        ),
    ]
