# Generated by Django 4.1.7 on 2023-05-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseProject", "0016_message_image_delete_imagemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="friendsOnly",
            field=models.BooleanField(default=False),
        ),
    ]
